sudo: false
language: python
python:
    - "2.7"

services:
    - mongodb

addons:
    apt:
        sources:
            - mongodb-3.2-precise
        packages:
            - mongodb-org-server

cache:
    pip: true
    directories:
        - $VIRTUAL_ENV/lib/node_modules

install:
    - pip install -r requirements.txt
    - ./test/bin/setup-integration-tests-ubuntu.sh

script:
    - SCITRAN_PERSISTENT_DB_PORT=27017 test/bin/run-tests-ubuntu.sh

after_success:
    - coveralls
